Select 
epd.EXPORT_PERMIT_DETAIL_NUMBER	
,epd.DESTINATION_COMPANY_NAME	
,epd.TRANSPORT_NAME	
,epd.ESTIMATED_SHIPPING_DATE	
,epd.OTHER_PORT_OF_EXPORT	
,epd.APPLICATION_DATE	
,epd.RECEIVED_DATE	
,epd.EXPORT_PERMIT_ISSUE_DATE	
,epd.RECEIPT_NUMBER	
,epd.EXPIRY_DATE	
,epd.PERMIT_VOLUME	
,epd.NUMBER_OF_PIECES	
,epd.FEE_IN_LIEU_VOLUME	
,epd.FEDERAL_PERMIT_NUMBER	
,epd.REMARKS	
,epd.CLIENT_NUMBER	
,epd.CLIENT_LOCN_CODE
,epd.EXEMPTION_NUMBER	
,epd.ORG_UNIT_NO	
,epd.EXPORT_SCALE_METHOD_CODE
,epd.EXPORT_TRANSPORT_TYPE_CODE
,epd.EXPORT_PORT_OF_EXPORT_CODE
,epd.EXPORT_PERMIT_STATUS_CODE	
,epd.EXPORT_COUNTRY_CODE	
,epd.EXPORT_GROWTH_TYPE_CODE
,ee.EXEMPTION_NUMBER	
,ee.APPROVED_VOLUME	
,ee.APPROVAL_DATE	
,ee.EXPIRY_DATE	
,ee.OTHER_CONDITIONS	
,ee.EXPORT_EXEMPTION_TYPE_CODE	
,ee.EXPORT_EXEMPTION_STATUS_CODE
,sd.PACKAGE_NUMBER
,sd.TIMBER_MARK AS EXPORT_SCALE_DETAIL_TM
,hla.TIMBER_MARK AS HAULING_AUTHORITY_TM
,hax.TIMBER_MARK AS HARVESTING_HAULING_XREF_TM
,hax.HVA_SKEY AS HARVESTING_HAULING_XREF_SKEY
,hgm.HVA_SKEY AS HARVEST_AUTHORITY_GEOM_SKEY
,haa.HVA_SKEY AS HARVESTING_AUTHORITY_SKEY
,hla.FOREST_FILE_ID AS HLA_FOREST_FILE_ID
,haa.FOREST_FILE_ID AS HAA_FOREST_FILE_ID
,hgm.GEOMETRY 
FROM EXPORT_PERMIT_DETAIL epd 
  left join EXPORT_EXEMPTION ee on (ee.EXEMPTION_NUMBER = epd.EXEMPTION_NUMBER)
  left join EXPORT_SCALE_DETAIL sd on (epd.EXPORT_PERMIT_DETAIL_NUMBER = sd.Export_scale_detail_id)
  left join HAULING_AUTHORITY hla on (sd.timber_mark = hla.timber_mark)
  left join HARVESTING_HAULING_XREF hax on (hax.timber_mark = hla.timber_mark and hax.primary_mark_ind = 'Y')
  left join HARVEST_AUTHORITY_GEOM hgm on (hgm.hva_skey = hax.hva_skey)
  left join HARVESTING_AUTHORITY haa on (haa.hva_skey = hax.hva_skey)